// GlobalStateContext.js
import React, { useState } from "react";
import GlobalStateContext from "./GlobalStateContext";
import { effect, useColorMode, useDisclosure } from "@chakra-ui/react";
import { v4 as uuidv4 } from "uuid";
import { TbClock2 } from "react-icons/tb";
import { CiWallet } from "react-icons/ci";
import { HiOutlineReceiptPercent } from "react-icons/hi2";
import { IoMdQrScanner } from "react-icons/io";
import { GrDocumentPdf } from "react-icons/gr";
import { AiOutlineFileGif } from "react-icons/ai";
import { MdOutlineNoFood } from "react-icons/md";
import { LuFuel } from "react-icons/lu";
import { GoGift } from "react-icons/go";
import { FaWifi } from "react-icons/fa";
import { SiBookstack } from "react-icons/si";
import Food from "../assets/icons/Food.png";
import Fuel from "../assets/icons/Fuel.png";
import Gift from "../assets/icons/gift.png";
import books from "../assets/icons/bookStack.png";
import telecom from "../assets/icons/telecom.png";
import gadget from "../assets/icons/gadget.png";
import foods from "../assets/icons/foods.png";
import { useForm } from "react-hook-form";
const getRandomDate = (start, end) => {
  const date = new Date(
    start.getTime() + Math.random() * (end.getTime() - start.getTime())
  );
  return date.toISOString();
};

const startDate = new Date(2020, 0, 1); // January 1, 2020
const endDate = new Date(); // Current date

export const generateUniqueId = () => {
  const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const digits = "0123456789";

  let id = "";

  // Generate three random uppercase letters
  for (let i = 0; i < 3; i++) {
    id += letters[Math.floor(Math.random() * letters.length)];
  }

  // Generate seven random digits
  for (let i = 0; i < 7; i++) {
    id += digits[Math.floor(Math.random() * digits.length)];
  }

  return id;
};

const GlobalStateProvider = ({ children }) => {
  const [isAuthenticate, setIsAuthenticate] = useState(false);

  const [employees, setEmployees] = useState([
    {
      id: 1,
      EmpID: "124589",
      Name: "Jackson",
      emailAddress: "in***@optifiimais.com",
      reportname: "Reimbursement report 2024",
      mobileNumber: "+91 ***8451254",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      datetime: "10 June, 2924 10 am",
      disburser: "Manav sain",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 2,
      EmpID: "124556",
      Name: "Status",
      reportname: "Reimbursement report 2024",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      Grade: "L1",
      disburser: "Manav sain",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      datetime: "10 June, 2924 10 am",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 3,
      EmpID: "124589",
      Name: "Status",
      disburser: "Manav sain",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 4,
      EmpID: "124589",
      disburser: "Manav sain",
      Name: "Status",
      emailAddress: "in***@optifiimais.com",
      datetime: "10 June, 2924 10 am",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 5,
      EmpID: "124589",
      Name: "Status",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      Department: "Sales",
      disburser: "Manav sain",
      Role: "Sr. Manager",
      status: "Inactive",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 6,
      EmpID: "124589",
      disburser: "Manav sain",
      Name: "Status",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Inactive",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 7,
      EmpID: "124589",
      Name: "Status",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 8,
      EmpID: "124589",
      Name: "Status",
      disburser: "Manav sain",
      emailAddress: "in***@optifiimais.com",
      reportname: "Reimbursement report 2024",
      mobileNumber: "+91 ***8451254",
      datetime: "10 June, 2924 10 am",
      reportamount: "₹ 50000",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Inactive",
      subMenu: [
        {
          wallet: "Food",
          walBal: "₹ 5000",
        },
        {
          wallet: "Travel",
          walBal: "₹ 7000",
        },
        {
          wallet: "Toor",
          walBal: "₹ 3000",
        },
      ],
      approver: "Reethik thota",
    },
    {
      id: 9,
      EmpID: "124589",
      Name: "Status",
      disburser: "Manav sain",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 10,
      EmpID: "124589",
      Name: "Status",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      disburser: "Manav sain",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Inactive",
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 10,
      EmpID: "124589",
      Name: "Status",
      disburser: "Manav sain",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
    {
      id: 11,
      EmpID: "124589",
      disburser: "Manav sain",
      Name: "Status",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 ***8451254",
      reportname: "Reimbursement report 2024",
      datetime: "10 June, 2924 10 am",
      Grade: "L1",
      Department: "Sales",
      Role: "Sr. Manager",
      status: "Active",
      reportamount: "₹ 50000",
      approver: "Reethik thota",
    },
  ]);

  const [reportsHistory, setReportsHistory] = useState([
    {
      id: 1,
      name: "Office Supplies - July 2024",
      lastUpdated: "31-07-2024 10:15 am",
      reportType: "Expense",
      totalExpense: 350.75,
      status: "Approved",
    },
    {
      id: 2,
      name: "Travel Reimbursement - Q2 2024",
      lastUpdated: "15-08-2024 02:45 pm",
      reportType: "Expense",
      totalExpense: 1250.0,
      status: "Approved",
    },
    {
      id: 3,
      name: "Client Meeting Expenses - August 2024",
      lastUpdated: "28-08-2024 09:30 am",
      reportType: "Expense",
      totalExpense: 600.5,
      status: "Fully Reimbursed",
    },
    {
      id: 4,
      name: "Marketing Campaign - Q3 2024",
      lastUpdated: "10-09-2024 11:00 am",
      reportType: "Expense",
      totalExpense: 2300.0,
      status: "Disapproved",
    },
    {
      id: 5,
      name: "Team Building Event - September 2024",
      lastUpdated: "22-09-2024 04:20 pm",
      reportType: "Expense",
      totalExpense: 800.0,
      status: "Fully Reimbursed",
    },
    {
      id: 6,
      name: "Office Renovation - Phase 1",
      lastUpdated: "30-09-2024 03:10 pm",
      reportType: "Expense",
      totalExpense: 4500.0,
      status: "Saved",
    },
    {
      id: 7,
      name: "Software Licenses - 2024 Renewal",
      lastUpdated: "05-10-2024 01:50 pm",
      reportType: "Expense",
      totalExpense: 3200.0,
      status: "Saved",
    },
    {
      id: 8,
      name: "Conference Attendance - October 2024",
      lastUpdated: "15-10-2024 09:00 am",
      reportType: "Expense",
      totalExpense: 1500.0,
      status: "Partially Reimbursed",
    },
    {
      id: 9,
      name: "Holiday Party - December 2024",
      lastUpdated: "20-12-2024 05:30 pm",
      reportType: "Expense",
      totalExpense: 2500.0,
      status: "Saved",
    },
    {
      id: 10,
      name: "Client Gifts - End of Year 2024",
      lastUpdated: "31-12-2024 02:00 pm",
      reportType: "Expense",
      totalExpense: 1200.0,
      status: "Approved",
    },
    {
      id: 11,
      name: "Training Programs - January 2025",
      lastUpdated: "15-01-2025 10:30 am",
      reportType: "Expense",
      totalExpense: 900.0,
      status: "Saved",
    },
    {
      id: 7,
      name: "Software Licenses - 2024 Renewal",
      lastUpdated: "05-10-2024 01:50 pm",
      reportType: "Expense",
      totalExpense: 3200.0,
      status: "Saved",
    },
    {
      id: 8,
      name: "Conference Attendance - October 2024",
      lastUpdated: "15-10-2024 09:00 am",
      reportType: "Expense",
      totalExpense: 1500.0,
      status: "Partially Reimbursed",
    },
    {
      id: 9,
      name: "Holiday Party - December 2024",
      lastUpdated: "20-12-2024 05:30 pm",
      reportType: "Expense",
      totalExpense: 2500.0,
      status: "Saved",
    },
    {
      id: 10,
      name: "Client Gifts - End of Year 2024",
      lastUpdated: "31-12-2024 02:00 pm",
      reportType: "Expense",
      totalExpense: 1200.0,
      status: "Approved",
    },
    {
      id: 11,
      name: "Training Programs - January 2025",
      lastUpdated: "15-01-2025 10:30 am",
      reportType: "Expense",
      totalExpense: 900.0,
      status: "Saved",
    },
    {
      id: 7,
      name: "Software Licenses - 2024 Renewal",
      lastUpdated: "05-10-2024 01:50 pm",
      reportType: "Expense",
      totalExpense: 3200.0,
      status: "Saved",
    },
    {
      id: 8,
      name: "Conference Attendance - October 2024",
      lastUpdated: "15-10-2024 09:00 am",
      reportType: "Expense",
      totalExpense: 1500.0,
      status: "Partially Reimbursed",
    },
    {
      id: 9,
      name: "Holiday Party - December 2024",
      lastUpdated: "20-12-2024 05:30 pm",
      reportType: "Expense",
      totalExpense: 2500.0,
      status: "Saved",
    },
    {
      id: 10,
      name: "Client Gifts - End of Year 2024",
      lastUpdated: "31-12-2024 02:00 pm",
      reportType: "Expense",
      totalExpense: 1200.0,
      status: "Approved",
    },
    {
      id: 11,
      name: "Training Programs - January 2025",
      lastUpdated: "15-01-2025 10:30 am",
      reportType: "Expense",
      totalExpense: 900.0,
      status: "Saved",
    },
  ]);

  // const [department, setDepartment] = useState([
  //   {
  //     "id": 1,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 2,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 3,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 4,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 5,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 6,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 7,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 8,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 9,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  //   {
  //     "id": 10,
  //     "department": "FInance",
  //     "role": "Sr. Manager",
  //     "createdBy": "Reethik Thota",
  //     "dateTime": "12 June 2024, 10.00 am",
  //     "approvedBy": "Pooja Patade",
  //   },
  // ]);

  // const [roles, setRoles] = useState([
  //   {
  //     "id": 1,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Published",
  //   },
  //   {
  //     "id": 2,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Published",
  //   },
  //   {
  //     "id": 3,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Saved as draft",
  //   },
  //   {
  //     "id": 4,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Published",
  //   },
  //   {
  //     "id": 5,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Saved as draft",
  //   },
  //   {
  //     "id": 6,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Saved as draft",
  //   },
  //   {
  //     "id": 7,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Saved as draft",
  //   },
  //   {
  //     "id": 8,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Saved as draft",
  //   },
  //   {
  //     "id": 9,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Published",
  //   },
  //   {
  //     "id": 10,
  //     "role": "Sr Manager",
  //     "department": "Finance",
  //     "createdDuration": "11 June 2024, 10 am",
  //     "createdBy": "Pooja Patade",
  //     "permissions": "Subadmin",
  //     "status": "Saved as draft",
  //   },
  //   {
  //     id: 2,
  //     name: "Travel Reimbursement - Q2 2024",
  //     lastUpdated: "15-08-2024 02:45 pm",
  //     reportType: "Expense",
  //     totalExpense: 1250.0,
  //     status: "Approved",
  //   },
  //   {
  //     id: 3,
  //     name: "Client Meeting Expenses - August 2024",
  //     lastUpdated: "28-08-2024 09:30 am",
  //     reportType: "Expense",
  //     totalExpense: 600.5,
  //     status: "Fully Reimbursed",
  //   },
  //   {
  //     id: 4,
  //     name: "Marketing Campaign - Q3 2024",
  //     lastUpdated: "10-09-2024 11:00 am",
  //     reportType: "Expense",
  //     totalExpense: 2300.0,
  //     status: "Disapproved",
  //   },
  //   {
  //     id: 5,
  //     name: "Team Building Event - September 2024",
  //     lastUpdated: "22-09-2024 04:20 pm",
  //     reportType: "Expense",
  //     totalExpense: 800.0,
  //     status: "Fully Reimbursed",
  //   },
  //   {
  //     id: 6,
  //     name: "Office Renovation - Phase 1",
  //     lastUpdated: "30-09-2024 03:10 pm",
  //     reportType: "Expense",
  //     totalExpense: 4500.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 7,
  //     name: "Software Licenses - 2024 Renewal",
  //     lastUpdated: "05-10-2024 01:50 pm",
  //     reportType: "Expense",
  //     totalExpense: 3200.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 8,
  //     name: "Conference Attendance - October 2024",
  //     lastUpdated: "15-10-2024 09:00 am",
  //     reportType: "Expense",
  //     totalExpense: 1500.0,
  //     status: "Partially Reimbursed",
  //   },
  //   {
  //     id: 9,
  //     name: "Holiday Party - December 2024",
  //     lastUpdated: "20-12-2024 05:30 pm",
  //     reportType: "Expense",
  //     totalExpense: 2500.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 10,
  //     name: "Client Gifts - End of Year 2024",
  //     lastUpdated: "31-12-2024 02:00 pm",
  //     reportType: "Expense",
  //     totalExpense: 1200.0,
  //     status: "Approved",
  //   },
  //   {
  //     id: 11,
  //     name: "Training Programs - January 2025",
  //     lastUpdated: "15-01-2025 10:30 am",
  //     reportType: "Expense",
  //     totalExpense: 900.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 7,
  //     name: "Software Licenses - 2024 Renewal",
  //     lastUpdated: "05-10-2024 01:50 pm",
  //     reportType: "Expense",
  //     totalExpense: 3200.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 8,
  //     name: "Conference Attendance - October 2024",
  //     lastUpdated: "15-10-2024 09:00 am",
  //     reportType: "Expense",
  //     totalExpense: 1500.0,
  //     status: "Partially Reimbursed",
  //   },
  //   {
  //     id: 9,
  //     name: "Holiday Party - December 2024",
  //     lastUpdated: "20-12-2024 05:30 pm",
  //     reportType: "Expense",
  //     totalExpense: 2500.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 10,
  //     name: "Client Gifts - End of Year 2024",
  //     lastUpdated: "31-12-2024 02:00 pm",
  //     reportType: "Expense",
  //     totalExpense: 1200.0,
  //     status: "Approved",
  //   },
  //   {
  //     id: 11,
  //     name: "Training Programs - January 2025",
  //     lastUpdated: "15-01-2025 10:30 am",
  //     reportType: "Expense",
  //     totalExpense: 900.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 7,
  //     name: "Software Licenses - 2024 Renewal",
  //     lastUpdated: "05-10-2024 01:50 pm",
  //     reportType: "Expense",
  //     totalExpense: 3200.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 8,
  //     name: "Conference Attendance - October 2024",
  //     lastUpdated: "15-10-2024 09:00 am",
  //     reportType: "Expense",
  //     totalExpense: 1500.0,
  //     status: "Partially Reimbursed",
  //   },
  //   {
  //     id: 9,
  //     name: "Holiday Party - December 2024",
  //     lastUpdated: "20-12-2024 05:30 pm",
  //     reportType: "Expense",
  //     totalExpense: 2500.0,
  //     status: "Saved",
  //   },
  //   {
  //     id: 10,
  //     name: "Client Gifts - End of Year 2024",
  //     lastUpdated: "31-12-2024 02:00 pm",
  //     reportType: "Expense",
  //     totalExpense: 1200.0,
  //     status: "Approved",
  //   },
  //   {
  //     id: 11,
  //     name: "Training Programs - January 2025",
  //     lastUpdated: "15-01-2025 10:30 am",
  //     reportType: "Expense",
  //     totalExpense: 900.0,
  //     status: "Saved",
  //   },
  // ]);

  const [department, setDepartment] = useState([
    {
      id: 1,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 2,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 3,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 4,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 5,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 6,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 7,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 8,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 9,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
    {
      id: 10,
      department: "FInance",
      role: "Sr. Manager",
      createdBy: "Reethik Thota",
      dateTime: "12 June 2024, 10.00 am",
      approvedBy: "Pooja Patade",
    },
  ]);

  const [roles, setRoles] = useState([
    {
      id: 1,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Published",
    },
    {
      id: 2,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Published",
    },
    {
      id: 3,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Saved as draft",
    },
    {
      id: 4,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Published",
    },
    {
      id: 5,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Saved as draft",
    },
    {
      id: 6,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Saved as draft",
    },
    {
      id: 7,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Saved as draft",
    },
    {
      id: 8,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Saved as draft",
    },
    {
      id: 9,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Published",
    },
    {
      id: 10,
      role: "Sr Manager",
      department: "Finance",
      createdDuration: "11 June 2024, 10 am",
      createdBy: "Pooja Patade",
      permissions: "Subadmin",
      status: "Saved as draft",
    },
  ]);

  const [employeePermissions, setEmployeePermissions] = useState([
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
    {
      id: "12451",
      name: "Kartikey Gautam",
      emailID: "mailto:jennydanny@optifii.com",
      department: "Finance",
      role: "Sr. Accountant",
      permissions: "Subadmin",
    },
  ]);

  // const [employeePermissions, setEmployeePermissions] = useState([
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  //   {
  //     "id": "12451",
  //     "name": "Kartikey Gautam",
  //     "emailID": "mailto:jennydanny@optifii.com",
  //     "department": "Finance",
  //     "role": "Sr. Accountant",
  //     "permissions": "Subadmin",
  //   },
  // ]);

  const [advanceStatus, setAdvanceStatus] = useState([
    {
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Approved",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Approved",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Approved",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Fully reimbursed",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Fully reimbursed",
      approver: "Sales",
      disburser: "Sales",
    },
  ]);

  // const [reimbursementStatus, setReimbursementStatus] = useState([
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Approved",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Approved",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Approved",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Fully reimbursed",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Fully reimbursed",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   }
  // ]);
  const [reimbursementStatus, setReimbursementStatus] = useState([
    {
      id: 1,
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Fully reimbursed",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      id: 2,
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Fully reimbursed",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      id: 3,
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Approved",
      approver: "Sales",
      disburser: "Sales",
    },
    {
      id: 4,
      reportName: "Jan 12, 2022",
      reportBy: "in***@optifiimais.com",
      reportAmount: "+91 ***8451254",
      dateTime: "Sales",
      orderStatus: "Approved",
      approver: "Sales",
      disburser: "Sales",
    },
  ]);

  // const [advanceStatus, setAdvanceStatus] = useState([
  //   {
  //     reportName: "Jan 12, 2022",
  //     reportBy: "in***@optifiimais.com",
  //     reportAmount: "+91 ***8451254",
  //     dateTime: "Sales",
  //     orderStatus: "Approved",
  //     approver: "Sales",
  //     disburser: "Sales",
  //   },
  //   {
  //     reportName: "Jan 12, 2022",
  //     reportBy: "in***@optifiimais.com",
  //     reportAmount: "+91 ***8451254",
  //     dateTime: "Sales",
  //     orderStatus: "Approved",
  //     approver: "Sales",
  //     disburser: "Sales",
  //   },
  //   {
  //     reportName: "Jan 12, 2022",
  //     reportBy: "in***@optifiimais.com",
  //     reportAmount: "+91 ***8451254",
  //     dateTime: "Sales",
  //     orderStatus: "Approved",
  //     approver: "Sales",
  //     disburser: "Sales",
  //   },
  //   {
  //     reportName: "Jan 12, 2022",
  //     reportBy: "in***@optifiimais.com",
  //     reportAmount: "+91 ***8451254",
  //     dateTime: "Sales",
  //     orderStatus: "Fully reimbursed",
  //     approver: "Sales",
  //     disburser: "Sales",
  //   },
  //   {
  //     reportName: "Jan 12, 2022",
  //     reportBy: "in***@optifiimais.com",
  //     reportAmount: "+91 ***8451254",
  //     dateTime: "Sales",
  //     orderStatus: "Fully reimbursed",
  //     approver: "Sales",
  //     disburser: "Sales",
  //   },
  // ]);

  // const [digital, setDigital] = useState([
  //   {
  //     id: 1,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Active",
  //     CardDeliveryStatus: "Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 2,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Active",
  //     CardDeliveryStatus: "Not Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 3,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Activate",
  //     CardDeliveryStatus: "Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 3,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Partially Active",
  //     CardDeliveryStatus: "Partially Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 4,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Active",
  //     CardDeliveryStatus: "Not Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 5,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Partially Active",
  //     CardDeliveryStatus: "Not Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 6,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Active",
  //     CardDeliveryStatus: "Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 7,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Activate",
  //     CardDeliveryStatus: "Delivered",
  //     quantity: "500",
  //   },
  //   {
  //     id: 8,
  //     orderid: "#451245",
  //     laodStatus: "Fully Loaded",
  //     dateTime: "10 June 2024, 10am",
  //     totalvaluation: "₹ 70,000",
  //     activationStatus: "Activate",
  //     CardDeliveryStatus: "Delivered",
  //     quantity: "500",
  //   },
  // ]);

  // const [advanceStatus, setAdvanceStatus] = useState([
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Approved",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Approved",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Approved",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Fully reimbursed",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },
  //   {
  //     "reportName": "Jan 12, 2022",
  //     "reportBy": "in***@optifiimais.com",
  //     "reportAmount": "+91 ***8451254",
  //     "dateTime": "Sales",
  //     "orderStatus": "Fully reimbursed",
  //     "approver": "Sales",
  //     "disburser": "Sales",
  //   },

  // ]
  // )

  const [digital, setDigital] = useState([
    {
      id: 1,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Active",
      CardDeliveryStatus: "Delivered",
      quantity: "500",
      status: "Distributed",
    },
    {
      id: 2,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Active",
      CardDeliveryStatus: "Not Delivered",
      quantity: "500",
      status: "Distributed",
    },
    {
      id: 3,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Activate",
      CardDeliveryStatus: "Delivered",
      quantity: "500",
      status: "Pending",
    },
    {
      id: 4,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Partially Active",
      CardDeliveryStatus: "Partially Delivered",
      quantity: "500",
      status: "Pending",
    },
    {
      id: 5,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Active",
      CardDeliveryStatus: "Not Delivered",
      quantity: "500",
      status: "Distributed",
    },
    {
      id: 6,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Partially Active",
      CardDeliveryStatus: "Not Delivered",
      quantity: "500",
      status: "Pending",
    },
    {
      id: 7,
      orderid: "#451245",
      laodStatus: "Fully Loaded",
      dateTime: "10 June 2024, 10am",
      totalvaluation: "₹ 70,000",
      activationStatus: "Active",
      CardDeliveryStatus: "Delivered",
      quantity: "500",
      status: "Distributed",
    },
  ]);

  // supprt and ticket

  const [SupportAndTicket, setSupportAndTicket] = useState([
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "On hold",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "On hold",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "On hold",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "On hold",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "Inactive",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "Inactive",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "In progress",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "In progress",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
    {
      TicketID: 124589,
      Subject:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi.",
      Status: "In progress",
      LastUpdate: "Jun 10, 2024",
      Support: "Reethik thota",
    },
  ]);

  const [AdvanceExpenseRequest, setAdvanceExpenseRequest] = useState([
    {
      id: 1,
      ReportName: "Advance expense report 2024",
      ReportBy: {
        profImage:
          "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        profName: "Raju",
      },
      ReportAmount: "₹ 50000",
      DateTime: "10 June, 2924 10 am",
      Approver: "Reethik thota",
      Disburser: "Manav sain",
      Action: "View",
    },
    {
      id: 2,
      ReportName: "Advance expense report 2024",
      ReportBy: {
        profImage:
          "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        profName: "Raju",
      },
      ReportAmount: "₹ 50000",
      DateTime: "10 June, 2924 10 am",
      Approver: "Reethik thota",
      Disburser: "Manav sain",
      Action: "View",
    },
    {
      id: 3,
      ReportName: "Advance expense report 2024",
      ReportBy: {
        profImage:
          "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        profName: "Raju",
      },
      ReportAmount: "₹ 50000",
      DateTime: "10 June, 2924 10 am",
      Approver: "Reethik thota",
      Disburser: "Manav sain",
      Action: "View",
    },
    {
      id: 4,
      ReportName: "Advance expense report 2024",
      ReportBy: {
        profImage:
          "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        profName: "Raju",
      },
      ReportAmount: "₹ 50000",
      DateTime: "10 June, 2924 10 am",
      Approver: "Reethik thota",
      Disburser: "Manav sain",
      Action: "View",
    },
    {
      id: 5,
      ReportName: "Advance expense report 2024",
      ReportBy: {
        profImage:
          "https://images.pexels.com/photos/771742/pexels-photo-771742.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        profName: "Raju",
      },
      ReportAmount: "₹ 50000",
      DateTime: "10 June, 2924 10 am",
      Approver: "Reethik thota",
      Disburser: "Manav sain",
      Action: "View",
    },
  ]);

  const [AdvanceExpenseRequestView, setAdvanceExpenseRequestView] = useState([
    {
      DateTime: "10 June, 2924 10 am",
      Merchant: "Dine in",
      Category: "Food",
      Paymentmode: "Expense card",
      ReimburseAmount: "₹ 50000",
      Bills: "",
      Disburser: "Manav sain",
      Action: "",
    },
    {
      DateTime: "10 June, 2924 10 am",
      Merchant: "Airtel postpaid",
      Category: "Telecom",
      Paymentmode: "Expense card",
      ReimburseAmount: "₹ 50000",
      Bills: "",
      Disburser: "Manav sain",
      Action: "",
    },
    {
      DateTime: "10 June, 2924 10 am",
      Merchant: "Lorem ipsme",
      Category: "Fuel",
      Paymentmode: "Expense card",
      ReimburseAmount: "₹ 50000",
      Bills: "",
      Disburser: "Manav sain",
      Action: "",
    },
    {
      DateTime: "10 June, 2924 10 am",
      Merchant: "Dine in",
      Category: "Food",
      Paymentmode: "Expense card",
      ReimburseAmount: "₹ 50000",
      Bills: "",
      Disburser: "Manav sain",
      Action: "",
    },
  ]);

  const [ApplicationStatus, setApplicationStatus] = useState([
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "10,000",
      ActiveStatus: "Active",
      emailAddressMobile: "+91 *** 154874",
      MemberSince: "5 July, 2023",
      Action: "Activate card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "10,000",
      ActiveStatus: "Activate",
      emailAddressMobile: "in***@optifiimais.com",
      MemberSince: "5 July, 2023",
      Action: "Activate card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "load Card",
      ActiveStatus: "Activate",
      emailAddressMobile: "+91 *** 154874",
      MemberSince: "5 July, 2023",
      Action: "Load card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "10,000",
      ActiveStatus: "Active",
      emailAddressMobile: "+91 *** 154874",
      MemberSince: "5 July, 2023",
      Action: "Load card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "load Card",
      ActiveStatus: "Activate",
      emailAddressMobile: "in***@optifiimais.com",
      MemberSince: "5 July, 2023",
      Action: "Load card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "load Card",
      ActiveStatus: "Activate",
      emailAddressMobile: "in***@optifiimais.com",
      MemberSince: "5 July, 2023",
      Action: "Activate card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "10,000",
      ActiveStatus: "Activate",
      emailAddressMobile: "in***@optifiimais.com",
      MemberSince: "5 July, 2023",
      Action: "Activate card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "10,000",
      ActiveStatus: "Activate",
      emailAddressMobile: "in***@optifiimais.com",
      MemberSince: "5 July, 2023",
      Action: "Load card",
    },
    {
      EmpID: 124589,
      Name: "Pooja Shah",
      emailAddress: "in***@optifiimais.com",
      mobileNumber: "+91 *** 154874",
      Department: "Sales",
      LoadStatus: "load Card",
      ActiveStatus: "Activate",
      emailAddressMobile: "in***@optifiimais.com",
      MemberSince: "5 July, 2023",
      Action: "Activate card",
    },
  ]);

  const [walletProgram, setWalletProgram] = useState([
    {
      id: 1,
      walletName: [{ name: "Food", icon: Food }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Active",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 2,
      walletName: [{ name: "Fuel", icon: Fuel }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Active",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 3,
      walletName: [{ name: "Gift", icon: Gift }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Active",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 4,
      walletName: [{ name: "Telecom", icon: telecom }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Saved as draft",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 5,
      walletName: [{ name: "Books & periodicals", icon: books }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Active",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 6,
      walletName: [{ name: "Learning & development", icon: books }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Active",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 7,
      walletName: [{ name: "Gadget & equipment", icon: gadget }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Active",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 8,
      walletName: [{ name: "Telecom", icon: telecom }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Pending",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
    {
      id: 9,
      walletName: [{ name: "Food", icon: Food }],
      WalletType: "Prefilled",
      department: "sales",
      status: "Pending",
      WalletAmount: "₹ 50,000",
      CreatedOn: "Jan 12, 2022",
      CreatedBy: "Jenny wilson",
    },
  ]);

  const [voucher, setVoucher] = useState([
    {
      id: 1,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Scheduled",
    },
    {
      id: 2,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Scheduled",
    },
    {
      id: 3,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Scheduled",
    },
    {
      id: 4,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Scheduled",
    },
    {
      id: 5,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Completed",
    },
    {
      id: 6,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Completed",
    },
    {
      id: 7,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Completed",
    },
    {
      id: 8,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Completed",
    },
    {
      id: 9,
      DateTime: "Jan 12, 2022, 10 am",
      EmployeesDepartment: "250 employees",
      TotalAmount: "₹ 50,000",
      OrderStatus: "Completed",
    },
  ]);

  // Recent report
  const [recentReports, setRecentReports] = useState([
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Approved",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Approved",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Approved",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
    {
      reportName: "Food for June 30",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
      approver: "Reethik Thota",
      disburser: "Reethik Thota L1",
    },
  ]);

  // Recent transaction

  const [recentTransaction, setRecentTransaction] = useState([
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
    {
      walletName: "Food",
      Card: "Visa card  **** 4831",
      dateTime: "Jun 10, 2024",
      Amount: "₹ 5000",
      Merchant: "Dine in",
    },
  ]);

  // Wallets EB&G
  const [walletExpense, setWalletExpense] = useState([
    {
      wallet: "Food",
      walletAmount: "₹ 5000",
      balanceRemaining: "₹ 5000",
      Status: "Active",
    },
    {
      wallet: "Gift",
      walletAmount: "₹ 7000",
      balanceRemaining: "₹ 5000",
      Status: "Active",
    },
    {
      wallet: "Gift",
      walletAmount: "₹ 8000",
      balanceRemaining: "₹ 5000",
      Status: "Inactve",
    },
    {
      wallet: "Travel",
      walletAmount: "₹ 8000",
      balanceRemaining: "₹ 5000",
      Status: "Active",
    },
  ]);

  // main dash

  const [dash, setDash] = useState([
    {
      id: 1,
      wallet: "Food",
      walletAmount: "₹ 70,000",
      balanceRemaining: "₹ 20,000",
      status: "Approved",
      totalEmployees: 500,
      users: 5,
      icon: foods,
    },
    {
      id: 2,
      wallet: "Fuel",
      walletAmount: "₹ 50,000",
      balanceRemaining: "₹ 15,000",
      status: "Approved",
      totalEmployees: 200,
      users: 3,
      icon: Fuel,
    },
    {
      id: 3,
      wallet: "Books & Periodicals",
      walletAmount: "₹ 100,000",
      balanceRemaining: "₹ 80,000",
      status: "Pending",
      totalEmployees: 300,
      users: 4,
      icon: books,
    },
    {
      id: 4,
      wallet: "Telecom",
      walletAmount: "₹ 100,000",
      balanceRemaining: "₹ 80,000",
      status: "Pending",
      totalEmployees: 300,
      users: 4,
      icon: telecom,
    },
  ]);

  const [transactionHistory, setTransactionHistory] = useState([
    {
      id: 1,
      employeeName: "Reethik thota",
      employeeID: "#356567",
      department: "Sales",
      wallet: "FOOD",
      merchant: "Dine In",
      natureExpense: "Reimbursed",
      dateTime: "12 July 24, 10am",
      amount: "₹ 5000",
    },
    {
      id: 2,
      employeeName: "Reethik thota",
      employeeID: "#356567",
      department: "Sales",
      wallet: "FOOD",
      merchant: "Dine In",
      natureExpense: "Reimbursed",
      dateTime: "12 July 24, 10am",
      amount: "₹ 5000",
    },
    {
      id: 3,
      employeeName: "Reethik thota",
      employeeID: "#356567",
      department: "Sales",
      wallet: "FOOD",
      merchant: "Dine In",
      natureExpense: "Reimbursed",
      dateTime: "12 July 24, 10am",
      amount: "₹ 5000",
    },
    {
      id: 4,
      employeeName: "Reethik thota",
      employeeID: "#356567",
      department: "Sales",
      wallet: "FOOD",
      merchant: "Dine In",
      natureExpense: "Reimbursed",
      dateTime: "12 July 24, 10am",
      amount: "₹ 5000",
    },
    {
      id: 5,
      employeeName: "Reethik thota",
      employeeID: "#356567",
      department: "Sales",
      wallet: "FOOD",
      merchant: "Dine In",
      natureExpense: "Reimbursed",
      dateTime: "12 July 24, 10am",
      amount: "₹ 5000",
    },
    {
      id: 6,
      employeeName: "Reethik thota",
      employeeID: "#356567",
      department: "Sales",
      wallet: "FOOD",
      merchant: "Dine In",
      natureExpense: "Reimbursed",
      dateTime: "12 July 24, 10am",
      amount: "₹ 5000",
    },
  ]);

  const [reportStatus, setReportStatus] = useState([
    {
      id: 1,
      reportName: "Food",
      // reportBy: "#356567",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
      approver: "Reimbursed",
      disburser: "12 July 24, 10am",
      action: "₹ 5000",
    },
    {
      id: 2,
      reportName: "Food",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Partially Reimbursed",
    },
    {
      id: 3,
      reportName: "Food",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
    },
    {
      id: 4,
      reportName: "Food",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Fully Reimbursed",
    },
    {
      id: 5,
      reportName: "Food",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Approved",
    },
    {
      id: 6,
      reportName: "Food",
      reportAmount: "₹ 5000",
      dateTime: "Jun 10, 2024",
      status: "Approved",
    },
  ]);

  const [viewReports, setViewReports] = useState([
    {
      id: 1,
      inVoice: "Invoice #01 - Dec 2023",
      amount: "₹ 5000",
      paidWallet: "Food",
      status: "Approved",
    },
    {
      id: 2,
      inVoice: "Invoice #01 - Dec 2023",
      amount: "₹ 5000",
      paidWallet: "Food",
      status: "Approved",
    },
    {
      id: 3,
      inVoice: "Invoice #01 - Dec 2023",
      amount: "₹ 5000",
      paidWallet: "Food",
      status: "Approved",
    },
    {
      id: 4,
      inVoice: "Invoice #01 - Dec 2023",
      amount: "₹ 5000",
      paidWallet: "Food",
      status: "Approved",
    },
    {
      id: 5,
      inVoice: "Invoice #01 - Dec 2023",
      amount: "₹ 5000",
      paidWallet: "Food",
      status: "Approved",
    },
  ]);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const [selectedCardIndex, setSelectedCardIndex] = useState(null);
  const [selectionCount, setSelectionCount] = useState(0);
  const [showAnotherComponent, setShowAnotherComponent] = useState(false);
  const [hasProceeded, setHasProceeded] = useState(false);

  const { isOpen, onOpen, onClose } = useDisclosure();
  return (
    <GlobalStateContext.Provider
      value={{
        selectedCardIndex,
        setSelectedCardIndex,
        selectionCount,
        setSelectionCount,
        showAnotherComponent,
        setShowAnotherComponent,
        hasProceeded,
        setHasProceeded,
        onOpen,
        isOpen,
        onClose,
        reportsHistory,
        setReportsHistory,
        isAuthenticate,
        setIsAuthenticate,
        employees,
        setEmployees,
        department,
        setDepartment,
        roles,
        setRoles,
        employeePermissions,
        setEmployeePermissions,
        reimbursementStatus,
        setReimbursementStatus,
        voucher,
        advanceStatus,
        setAdvanceStatus,
        digital,
        setDigital,
        ApplicationStatus,
        // setAdvanceStatus,
        AdvanceExpenseRequest,
        setAdvanceExpenseRequest,
        AdvanceExpenseRequestView,
        setAdvanceExpenseRequestView,
        walletProgram,
        SupportAndTicket,
        setSupportAndTicket,
        recentReports,
        setRecentReports,
        recentTransaction,
        setRecentTransaction,
        useForm,
        // recentReports,
        // setRecentReports,
        // recentTransaction,
        // setRecentTransaction,
        walletExpense,
        setWalletExpense,
        dash,
        setDash,
        transactionHistory,
        setTransactionHistory,
        reportStatus,
        setReportStatus,
        viewReports,
        setViewReports,
      }}
    >
      {children}
    </GlobalStateContext.Provider>
  );
};
export default GlobalStateProvider;
